// New User
POST http://localhost:3030/user/register
Content-Type: application/json

{ "username": "miguelsolans", "password": "IAmForgetful", "email": "dev.miguelsolans@gmail.com", "fullName": "Carlos Miguel Rebelo Solans" }

###

// New User
POST http://localhost:3030/user/register
Content-Type: application/json

{ "username": "dichico", "password": "passwordforte", "email": "dichico.dev@uminho.pt", "fullName": "Diogo Francisco Araújo Leite Costa" }

###

POST http://localhost:3030/user/login
Content-Type: application/json

{ "username": "miguelsolans", "password": "IAmForgetful"}

###